"""add_auth_picks_notifications

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-21 21:24:34.703436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_anon_identities_id'), 'anon_identities', ['id'], unique=False)
    op.create_index(op.f('ix_anon_identities_last_seen'), 'anon_identities', ['last_seen'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('stripe', 'apple_iap', 'google_play', name='entitlementsource', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked', 'expired', name='entitlementstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlements_id'), 'entitlements', ['id'], unique=False)
    op.create_index(op.f('ix_entitlements_user_id'), 'entitlements', ['user_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('injury_alert', 'deadline_reminder', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('sent', 'failed', name='notificationstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_log_user_sent', 'notification_log', ['user_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_notification_log_id'), 'notification_log', ['id'], unique=False)
    op.create_table('notification_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('injury_alerts', sa.Boolean(), nullable=False),
    sa.Column('deadline_alerts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_prefs_id'), 'notification_prefs', ['id'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('(user_id IS NOT NULL AND identity_id IS NULL) OR (user_id IS NULL AND identity_id IS NOT NULL)', name='ck_owner_single_identity'),
    sa.ForeignKeyConstraint(['identity_id'], ['anon_identities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_token')
    )
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_last_seen'), 'user_devices', ['last_seen'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'game_date', name='uq_pick_owner_date')
    )
    op.create_index('ix_pick_game_date', 'picks', ['game_date'], unique=False)
    op.create_index(op.f('ix_picks_id'), 'picks', ['id'], unique=False)
    op.drop_index(op.f('ix_ttfl_scores_id'), table_name='fantasy_scores')
    op.create_index(op.f('ix_fantasy_scores_id'), 'fantasy_scores', ['id'], unique=False)
    op.drop_column('games', 'is_back2back_home')
    op.drop_column('games', 'is_back2back_away')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_back2back_away', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('is_back2back_home', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_fantasy_scores_id'), table_name='fantasy_scores')
    op.create_index(op.f('ix_ttfl_scores_id'), 'fantasy_scores', ['id'], unique=False)
    op.drop_index(op.f('ix_picks_id'), table_name='picks')
    op.drop_index('ix_pick_game_date', table_name='picks')
    op.drop_table('picks')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_last_seen'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_notification_prefs_id'), table_name='notification_prefs')
    op.drop_table('notification_prefs')
    op.drop_index(op.f('ix_notification_log_id'), table_name='notification_log')
    op.drop_index('ix_notif_log_user_sent', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_entitlements_user_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_id'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_anon_identities_last_seen'), table_name='anon_identities')
    op.drop_index(op.f('ix_anon_identities_id'), table_name='anon_identities')
    op.drop_table('anon_identities')
    # ### end Alembic commands ###
